#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
COMMANDS_DIR="$CLAUDE_DIR/commands"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

link() {
  local src="$1"
  local dst="$2"
  if [ -e "$dst" ] && [ ! -L "$dst" ]; then
    echo -e "  ${YELLOW}skipped${NC}  $dst (file already exists and is not a symlink)"
    return
  fi
  ln -sf "$src" "$dst"
  echo -e "  ${GREEN}linked${NC}   $dst"
}

echo ""
echo "Installing pycemrg-context into $CLAUDE_DIR"
echo ""

mkdir -p "$COMMANDS_DIR"

for cmd in "$REPO_DIR/commands/"*.md; do
  name="$(basename "$cmd")"
  link "$cmd" "$COMMANDS_DIR/$name"
done

# Generate LIBRARY_PATHS.md from detected sibling directories
PATHS_FILE="$REPO_DIR/LIBRARY_PATHS.md"
PARENT_DIR="$(dirname "$REPO_DIR")"

declare -A LIBRARIES=(
  ["pycemrg-core"]="pycemrg"
  ["pycemrg-image-analysis"]="pycemrg-image-analysis"
  ["pycemrg-model-creation"]="pycemrg-model-creation"
)

echo ""
echo "Detecting library paths..."
echo ""

{
  echo "# pycemrg Suite — Library Paths"
  echo ""
  echo "Generated by install.sh. Do not edit manually — re-run install.sh to update."
  echo ""
  printf "| %-22s | %-50s |\n" "Library" "Path"
  printf "| %-22s | %-50s |\n" "----------------------" "--------------------------------------------------"
} > "$PATHS_FILE"

for lib in "pycemrg-core" "pycemrg-image-analysis" "pycemrg-model-creation"; do
  dir_name="${LIBRARIES[$lib]}"
  candidate="$PARENT_DIR/$dir_name"
  if [ -d "$candidate" ]; then
    printf "| %-22s | %-50s |\n" "$lib" "$candidate" >> "$PATHS_FILE"
    echo -e "  ${GREEN}found${NC}    $lib → $candidate"
  else
    printf "| %-22s | %-50s |\n" "$lib" "NOT FOUND — set manually in LIBRARY_PATHS.md" >> "$PATHS_FILE"
    echo -e "  ${RED}missing${NC}  $lib (expected $candidate)"
  fi
done

echo ""
echo -e "  ${GREEN}written${NC}  $PATHS_FILE"
echo ""
echo "Done. Start a new Claude Code session to pick up the changes."
echo ""
